---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: macvtap-cni
allowHostNetwork: true
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostPID: false
allowHostPorts: false
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:default:macvtap-cni
volumes:
  - hostPath
